import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, CreateDateColumn, UpdateDateColumn, Index } from 'typeorm';
import { User } from './user.entity';
import { Company } from './company.entity';

export enum AlertType {
  PRICE_ABOVE = 'price_above',
  PRICE_BELOW = 'price_below',
  PERCENT_CHANGE = 'percent_change',
  VOLUME_SPIKE = 'volume_spike',
  NEWS_MENTION = 'news_mention',
  REGULATORY_UPDATE = 'regulatory_update',
}

export enum AlertStatus {
  ACTIVE = 'active',
  TRIGGERED = 'triggered',
  EXPIRED = 'expired',
  DISABLED = 'disabled',
}

@Entity('price_alerts')
@Index(['userId', 'companyId'])
export class PriceAlert {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'uuid' })
  userId: string;

  @Column({ type: 'uuid' })
  companyId: string;

  @Column({
    type: 'enum',
    enum: AlertType,
    default: AlertType.PRICE_ABOVE,
  })
  alertType: AlertType;

  @Column('decimal', { precision: 12, scale: 4 })
  targetValue: number;

  @Column('decimal', { precision: 12, scale: 4, nullable: true })
  currentValue: number;

  @Column({
    type: 'enum',
    enum: AlertStatus,
    default: AlertStatus.ACTIVE,
  })
  status: AlertStatus;

  @Column({ length: 500, nullable: true })
  message: string;

  @Column({ default: true })
  notifyPush: boolean;

  @Column({ default: false })
  notifyEmail: boolean;

  @Column({ default: true })
  notifyInApp: boolean;

  @Column({ default: false })
  isAutoGenerated: boolean;

  @Column({ type: 'timestamp', nullable: true })
  triggeredAt: Date;

  @Column({ type: 'timestamp', nullable: true })
  expiresAt: Date;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;

  @ManyToOne(() => User)
  user: User;

  @ManyToOne(() => Company)
  company: Company;
}
