import { Injectable, NotFoundException } from '@nestjs/common';
import { AlertType, AlertStatus } from '../common/entities/price-alert.entity';
import { CreateAlertDto } from './dto/create-alert.dto';
import { UpdateAlertDto } from './dto/update-alert.dto';

@Injectable()
export class PriceAlertsService {
  private alerts: any[] = [
    {
      id: 'a1',
      userId: '1',
      companyId: '1',
      companyName: 'Safaricom PLC',
      ticker: 'SCOM',
      alertType: AlertType.PRICE_BELOW,
      targetValue: 24.00,
      currentValue: 25.75,
      status: AlertStatus.ACTIVE,
      message: 'Alert me if Safaricom drops below KES 24',
      notifyPush: true,
      notifyEmail: false,
      notifyInApp: true,
      isAutoGenerated: false,
      triggeredAt: null,
      expiresAt: new Date('2026-03-10').toISOString(),
      createdAt: new Date('2026-02-01').toISOString(),
      updatedAt: new Date('2026-02-10').toISOString(),
    },
    {
      id: 'a2',
      userId: '1',
      companyId: '2',
      companyName: 'Equity Group Holdings',
      ticker: 'EQTY',
      alertType: AlertType.PERCENT_CHANGE,
      targetValue: 5.0,
      currentValue: -1.52,
      status: AlertStatus.ACTIVE,
      message: 'Notify on 5% price movement in Equity Group',
      notifyPush: true,
      notifyEmail: true,
      notifyInApp: true,
      isAutoGenerated: false,
      triggeredAt: null,
      expiresAt: null,
      createdAt: new Date('2026-02-05').toISOString(),
      updatedAt: new Date('2026-02-10').toISOString(),
    },
    {
      id: 'a3',
      userId: '1',
      companyId: '16',
      companyName: 'FinTech Africa Ltd',
      ticker: 'FTAF',
      alertType: AlertType.PRICE_ABOVE,
      targetValue: 22.00,
      currentValue: 22.80,
      status: AlertStatus.TRIGGERED,
      message: 'Auto-generated: FinTech stock surpasses KES 22 after CMA announcement',
      notifyPush: true,
      notifyEmail: false,
      notifyInApp: true,
      isAutoGenerated: true,
      triggeredAt: new Date('2026-02-09').toISOString(),
      expiresAt: null,
      createdAt: new Date('2026-02-08').toISOString(),
      updatedAt: new Date('2026-02-09').toISOString(),
    },
    {
      id: 'a4',
      userId: '1',
      companyId: '17',
      companyName: 'M-Pay Holdings',
      ticker: 'MPAY',
      alertType: AlertType.PERCENT_CHANGE,
      targetValue: 4.0,
      currentValue: 9.86,
      status: AlertStatus.TRIGGERED,
      message: 'Auto-generated: M-Pay moves >4% within 2 days of CMA announcement',
      notifyPush: true,
      notifyEmail: false,
      notifyInApp: true,
      isAutoGenerated: true,
      triggeredAt: new Date('2026-02-10').toISOString(),
      expiresAt: null,
      createdAt: new Date('2026-02-08').toISOString(),
      updatedAt: new Date('2026-02-10').toISOString(),
    },
    {
      id: 'a5',
      userId: '1',
      companyId: '10',
      companyName: 'Kenya Power',
      ticker: 'KPLC',
      alertType: AlertType.VOLUME_SPIKE,
      targetValue: 15000000,
      currentValue: 12000000,
      status: AlertStatus.ACTIVE,
      message: 'Alert on unusual volume spike for KPLC',
      notifyPush: true,
      notifyEmail: false,
      notifyInApp: true,
      isAutoGenerated: false,
      triggeredAt: null,
      expiresAt: null,
      createdAt: new Date('2026-02-03').toISOString(),
      updatedAt: new Date('2026-02-10').toISOString(),
    },
  ];

  private alertIdCounter = 6;

  async getUserAlerts(userId: string, status?: string) {
    let userAlerts = this.alerts.filter(a => a.userId === userId);
    if (status) {
      userAlerts = userAlerts.filter(a => a.status === status);
    }
    return userAlerts.sort(
      (a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime(),
    );
  }

  async getAlertById(alertId: string, userId: string) {
    const alert = this.alerts.find(a => a.id === alertId && a.userId === userId);
    if (!alert) {
      throw new NotFoundException('Alert not found');
    }
    return alert;
  }

  async createAlert(userId: string, dto: CreateAlertDto) {
    const companyMap = {
      '1': { name: 'Safaricom PLC', ticker: 'SCOM', currentPrice: 25.75 },
      '2': { name: 'Equity Group Holdings', ticker: 'EQTY', currentPrice: 48.50 },
      '3': { name: 'KCB Group', ticker: 'KCB', currentPrice: 42.25 },
      '4': { name: 'East African Breweries', ticker: 'EABL', currentPrice: 155.00 },
      '5': { name: 'BAT Kenya', ticker: 'BAT', currentPrice: 350.00 },
      '6': { name: 'Stanbic Holdings', ticker: 'SBIC', currentPrice: 112.00 },
      '7': { name: 'Co-operative Bank', ticker: 'COOP', currentPrice: 14.75 },
      '8': { name: 'ABSA Bank Kenya', ticker: 'ABSA', currentPrice: 13.90 },
      '9': { name: 'NCBA Group', ticker: 'NCBA', currentPrice: 44.50 },
      '10': { name: 'Kenya Power', ticker: 'KPLC', currentPrice: 3.20 },
      '16': { name: 'FinTech Africa Ltd', ticker: 'FTAF', currentPrice: 22.80 },
      '17': { name: 'M-Pay Holdings', ticker: 'MPAY', currentPrice: 15.60 },
    };

    const company = companyMap[dto.companyId];
    if (!company) {
      throw new NotFoundException('Company not found');
    }

    const alert = {
      id: `a${this.alertIdCounter++}`,
      userId,
      companyId: dto.companyId,
      companyName: company.name,
      ticker: company.ticker,
      alertType: dto.alertType,
      targetValue: dto.targetValue,
      currentValue: company.currentPrice,
      status: AlertStatus.ACTIVE,
      message: dto.message || null,
      notifyPush: dto.notifyPush ?? true,
      notifyEmail: dto.notifyEmail ?? false,
      notifyInApp: dto.notifyInApp ?? true,
      isAutoGenerated: false,
      triggeredAt: null,
      expiresAt: dto.expiresAt || null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    this.alerts.push(alert);
    return alert;
  }

  async updateAlert(alertId: string, userId: string, dto: UpdateAlertDto) {
    const alert = this.alerts.find(a => a.id === alertId && a.userId === userId);
    if (!alert) {
      throw new NotFoundException('Alert not found');
    }

    Object.assign(alert, {
      ...dto,
      updatedAt: new Date().toISOString(),
    });

    return alert;
  }

  async deleteAlert(alertId: string, userId: string) {
    const index = this.alerts.findIndex(a => a.id === alertId && a.userId === userId);
    if (index === -1) {
      throw new NotFoundException('Alert not found');
    }

    this.alerts.splice(index, 1);
    return { message: 'Alert deleted successfully' };
  }

  async disableAlert(alertId: string, userId: string) {
    const alert = this.alerts.find(a => a.id === alertId && a.userId === userId);
    if (!alert) {
      throw new NotFoundException('Alert not found');
    }

    alert.status = AlertStatus.DISABLED;
    alert.updatedAt = new Date().toISOString();
    return alert;
  }

  async getTriggeredAlerts(userId: string) {
    return this.alerts
      .filter(a => a.userId === userId && a.status === AlertStatus.TRIGGERED)
      .sort((a, b) => new Date(b.triggeredAt).getTime() - new Date(a.triggeredAt).getTime());
  }

  async getAlertStats(userId: string) {
    const userAlerts = this.alerts.filter(a => a.userId === userId);
    return {
      total: userAlerts.length,
      active: userAlerts.filter(a => a.status === AlertStatus.ACTIVE).length,
      triggered: userAlerts.filter(a => a.status === AlertStatus.TRIGGERED).length,
      expired: userAlerts.filter(a => a.status === AlertStatus.EXPIRED).length,
      disabled: userAlerts.filter(a => a.status === AlertStatus.DISABLED).length,
      autoGenerated: userAlerts.filter(a => a.isAutoGenerated).length,
      manual: userAlerts.filter(a => !a.isAutoGenerated).length,
      byType: {
        priceAbove: userAlerts.filter(a => a.alertType === AlertType.PRICE_ABOVE).length,
        priceBelow: userAlerts.filter(a => a.alertType === AlertType.PRICE_BELOW).length,
        percentChange: userAlerts.filter(a => a.alertType === AlertType.PERCENT_CHANGE).length,
        volumeSpike: userAlerts.filter(a => a.alertType === AlertType.VOLUME_SPIKE).length,
        newsMention: userAlerts.filter(a => a.alertType === AlertType.NEWS_MENTION).length,
        regulatoryUpdate: userAlerts.filter(a => a.alertType === AlertType.REGULATORY_UPDATE).length,
      },
    };
  }
}
