#!/bin/bash

# Security Hardening Script for NSE Intelligence Platform
# Implements comprehensive security measures for production deployment

set -e

echo "🔒 Implementing security hardening measures..."

# Create security configurations directory
mkdir -p security
mkdir -p security/iptables
mkdir -p security/fail2ban
mkdir -p security/apparmor

# 1. Firewall Configuration
echo "🛡️ Setting up firewall rules..."
cat > security/iptables/rules.v4 << 'EOF'
# NSE Intelligence Platform - Firewall Rules
# Generated by security hardening script

# Flush existing rules
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]

# Allow loopback
-A INPUT -i lo -j ACCEPT

# Allow established connections
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# Allow SSH (rate limited)
-A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW -m recent --set
-A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 4 -j DROP
-A INPUT -p tcp --dport 22 -j ACCEPT

# Allow HTTP and HTTPS
-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -p tcp --dport 443 -j ACCEPT

# Allow monitoring ports (internal only)
-A INPUT -s 10.0.0.0/8 -p tcp --dport 9090 -j ACCEPT  # Prometheus
-A INPUT -s 10.0.0.0/8 -p tcp --dport 3001 -j ACCEPT  # Grafana

# Allow Docker internal traffic
-A INPUT -s 172.16.0.0/12 -j ACCEPT
-A INPUT -s 192.168.0.0/16 -j ACCEPT

# Rate limiting for HTTP
-A INPUT -p tcp --dport 80 -m conntrack --ctstate NEW -m recent --set
-A INPUT -p tcp --dport 80 -m conntrack --ctstate NEW -m recent --update --seconds 10 --hitcount 20 -j DROP

-A INPUT -p tcp --dport 443 -m conntrack --ctstate NEW -m recent --set
-A INPUT -p tcp --dport 443 -m conntrack --ctstate NEW -m recent --update --seconds 10 --hitcount 20 -j DROP

# Log dropped packets
-A INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables dropped: " --log-level 4

COMMIT
EOF

# 2. Fail2Ban Configuration
echo "⚖️ Setting up Fail2Ban..."
cat > security/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
backend = systemd
destemail = admin@your-domain.com
sender = fail2ban@your-domain.com
mta = sendmail

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600

[nginx-http-auth]
enabled = true
filter = nginx-http-auth
logpath = /var/log/nginx/error.log
maxretry = 3
bantime = 3600

[nginx-limit-req]
enabled = true
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 10
bantime = 600

[nginx-botsearch]
enabled = true
filter = nginx-botsearch
logpath = /var/log/nginx/access.log
maxretry = 2
bantime = 86400

[postfix]
enabled = true
filter = postfix
logpath = /var/log/mail.log
maxretry = 3
bantime = 3600

[nginx-noscript]
enabled = true
filter = nginx-noscript
logpath = /var/log/nginx/access.log
maxretry = 6
bantime = 86400

[nginx-badbots]
enabled = true
filter = nginx-badbots
logpath = /var/log/nginx/access.log
maxretry = 2
bantime = 86400

[nginx-noproxy]
enabled = true
filter = nginx-noproxy
logpath = /var/log/nginx/access.log
maxretry = 2
bantime = 86400
EOF

# 3. Security Headers Configuration
echo "🔐 Creating security headers configuration..."
cat > security/security-headers.conf << 'EOF'
# Content Security Policy
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' wss: https:; frame-ancestors 'none'; form-action 'self';" always;

# X-Frame-Options
add_header X-Frame-Options DENY always;

# X-Content-Type-Options
add_header X-Content-Type-Options nosniff always;

# X-XSS-Protection
add_header X-XSS-Protection "1; mode=block" always;

# Referrer Policy
add_header Referrer-Policy "strict-origin-when-cross-origin" always;

# Strict-Transport-Security
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

# Permissions Policy
add_header Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=()" always;

# Remove Server header
proxy_hide_header Server;
server_tokens off;
EOF

# 4. Application Security Configuration
echo "🛡️ Creating application security configuration..."
cat > security/app-security.yml << 'EOF'
# Application Security Configuration

# JWT Settings
jwt:
  secret_length: 256
  algorithm: HS256
  expires_in: 7d
  refresh_expires_in: 30d

# Password Security
password:
  min_length: 12
  require_uppercase: true
  require_lowercase: true
  require_numbers: true
  require_symbols: true
  max_age_days: 90

# Rate Limiting
rate_limiting:
  login:
    window: 15m
    max_attempts: 5
  api:
    window: 1m
    max_requests: 100
  upload:
    window: 1h
    max_uploads: 10

# Session Security
session:
  timeout: 30m
  secure: true
  http_only: true
  same_site: strict

# CORS Settings
cors:
  allowed_origins:
    - "https://your-domain.com"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Authorization
    - Content-Type
    - Accept
  credentials: true

# Input Validation
validation:
  max_file_size: 10MB
  allowed_file_types:
    - pdf
    - doc
    - docx
    - xls
    - xlsx
    - png
    - jpg
    - jpeg
  sanitize_html: true
  sql_injection_protection: true
  xss_protection: true

# Audit Logging
audit:
  log_all_requests: true
  log_auth_events: true
  log_data_changes: true
  log_failed_attempts: true
  retention_days: 2555
EOF

# 5. Docker Security Configuration
echo "🐳 Creating Docker security configuration..."
cat > security/docker-security.yml << 'EOF'
# Docker Security Configuration

# Container Security
containers:
  run_as_non_root: true
  read_only_filesystem: true
  no_new_privileges: true
  drop_capabilities:
    - ALL
  add_capabilities: []
  user_namespace: true
  seccomp_profile: true
  apparmor_profile: true
  resource_limits:
    memory: 512m
    cpu: 1.0
    pids: 100

# Network Security
networks:
  internal_networks:
    - nse-internal
  firewall_rules:
    - block_all_ingress
    - allow_established
    - allow_specific_ports:
      - 80
      - 443
      - 22

# Image Security
images:
  scan_for_vulnerabilities: true
  use_minimal_base_images: true
  fix_vulnerabilities: true
  sign_images: true

# Secrets Management
secrets:
  use_docker_secrets: true
  encrypt_at_rest: true
  rotate_secrets: true
  audit_secrets_access: true
EOF

# 6. Database Security Configuration
echo "🗄️ Creating database security configuration..."
cat > security/database-security.yml << 'EOF'
# Database Security Configuration

# PostgreSQL Security
postgresql:
  ssl_mode: require
  ssl_cert_file: /etc/ssl/certs/server.crt
  ssl_key_file: /etc/ssl/private/server.key
  ssl_ca_file: /etc/ssl/certs/ca.crt
  
  # Connection Security
  max_connections: 100
  connection_timeout: 30s
  authentication_timeout: 60s
  
  # User Permissions
  application_user:
    privileges:
      - SELECT
      - INSERT
      - UPDATE
      - DELETE
    restricted_tables:
      - users
      - audit_log
  
  # Audit Settings
  log_connections: true
  log_disconnections: true
  log_statements: all
  audit_trail: true

# Redis Security
redis:
  require_password: true
  rename_commands:
    - CONFIG: ""
    - FLUSHDB: ""
    - FLUSHALL: ""
    - KEYS: ""
  ssl_enabled: true
  ssl_cert_file: /etc/ssl/certs/redis.crt
  ssl_key_file: /etc/ssl/private/redis.key
  
# Elasticsearch Security
elasticsearch:
  enable_security: true
  ssl_enabled: true
  audit_enabled: true
  index_permissions:
    read_only_users:
      - monitoring
    admin_users:
      - admin
  field_level_security: true
EOF

# 7. Security Monitoring Script
echo "🔍 Creating security monitoring script..."
cat > scripts/security-monitor.sh << 'EOF'
#!/bin/bash

# Security Monitoring Script
# Monitors security events and sends alerts

set -e

ALERT_EMAIL=${ALERT_EMAIL:-"admin@your-domain.com"}
LOG_FILE="/var/log/security-monitor.log"

log_event() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOG_FILE"
}

# Check for suspicious login attempts
check_suspicious_logins() {
    local failed_logins=$(grep "authentication failure" /var/log/auth.log | grep "$(date '+%b %d')" | wc -l)
    if [ "$failed_logins" -gt 10 ]; then
        log_event "HIGH: $failed_logins failed login attempts detected today"
        # echo "High number of failed login attempts: $failed_logins" | mail -s "Security Alert" $ALERT_EMAIL
    fi
}

# Check for unusual network traffic
check_network_traffic() {
    local connections=$(netstat -an | grep :443 | grep ESTABLISHED | wc -l)
    if [ "$connections" -gt 1000 ]; then
        log_event "MEDIUM: Unusually high number of HTTPS connections: $connections"
    fi
}

# Check for file integrity
check_file_integrity() {
    if [ -f "/opt/nse-intelligence/security/file_hashes.txt" ]; then
        while read -r line; do
            file=$(echo "$line" | cut -d' ' -f3-)
            expected_hash=$(echo "$line" | cut -d' ' -f1)
            if [ -f "$file" ]; then
                actual_hash=$(sha256sum "$file" | cut -d' ' -f1)
                if [ "$expected_hash" != "$actual_hash" ]; then
                    log_event "HIGH: File integrity violation detected: $file"
                    # echo "File integrity violation: $file" | mail -s "Security Alert" $ALERT_EMAIL
                fi
            fi
        done < /opt/nse-intelligence/security/file_hashes.txt
    fi
}

# Check for SSL certificate expiry
check_ssl_expiry() {
    if [ -f "nginx/ssl/cert.pem" ]; then
        local expiry_date=$(openssl x509 -in nginx/ssl/cert.pem -noout -enddate | cut -d= -f2)
        local expiry_timestamp=$(date -d "$expiry_date" +%s)
        local current_timestamp=$(date +%s)
        local days_until_expiry=$(( (expiry_timestamp - current_timestamp) / 86400 ))
        
        if [ "$days_until_expiry" -lt 30 ]; then
            log_event "HIGH: SSL certificate expires in $days_until_expiry days"
            # echo "SSL certificate expires in $days_until_expiry days" | mail -s "SSL Certificate Alert" $ALERT_EMAIL
        fi
    fi
}

# Check for Docker container security
check_docker_security() {
    # Check for containers running as root
    local root_containers=$(docker ps --format "table {{.Names}}" | grep -v NAMES | while read container; do
        if docker inspect "$container" | grep -q '"User": ""'; then
            echo "$container"
        fi
    done)
    
    if [ -n "$root_containers" ]; then
        log_event "MEDIUM: Containers running as root: $root_containers"
    fi
    
    # Check for exposed Docker socket
    if docker ps --format "{{.Mounts}}" | grep -q "/var/run/docker.sock"; then
        log_event "HIGH: Docker socket exposed to container"
    fi
}

# Main monitoring loop
log_event "Starting security monitoring check"

check_suspicious_logins
check_network_traffic
check_file_integrity
check_ssl_expiry
check_docker_security

log_event "Security monitoring check completed"
EOF

chmod +x scripts/security-monitor.sh

# 8. Security Audit Script
echo "🔍 Creating security audit script..."
cat > scripts/security-audit.sh << 'EOF'
#!/bin/bash

# Security Audit Script
# Performs comprehensive security audit

set -e

echo "🔍 Performing security audit..."

# Check system updates
echo "📦 Checking for system updates..."
if command -v apt &> /dev/null; then
    apt list --upgradable 2>/dev/null | grep -v "WARNING" | wc -l
fi

# Check open ports
echo "🌐 Checking open ports..."
netstat -tuln | grep LISTEN

# Check user accounts
echo "👥 Checking user accounts..."
awk -F: '($3 >= 1000) {print $1}' /etc/passwd

# Check sudo access
echo "🔐 Checking sudo access..."
getent group sudo

# Check file permissions
echo "📁 Checking critical file permissions..."
ls -la /etc/passwd /etc/shadow /etc/sudoers 2>/dev/null

# Check Docker security
echo "🐳 Checking Docker security..."
docker version --format '{{.Server.Version}}'
docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"

# Check SSL certificates
echo "🔐 Checking SSL certificates..."
if [ -f "nginx/ssl/cert.pem" ]; then
    openssl x509 -in nginx/ssl/cert.pem -noout -dates
fi

# Check firewall status
echo "🛡️ Checking firewall status..."
if command -v ufw &> /dev/null; then
    ufw status
fi

echo "✅ Security audit completed"
EOF

chmod +x scripts/security-audit.sh

echo "✅ Security hardening measures implemented!"
echo "📁 Security configurations created in security/"
echo "🔍 Run security monitoring: ./scripts/security-monitor.sh"
echo "🔍 Run security audit: ./scripts/security-audit.sh"
